
Tracker:AddLocations("locations/lake_orangatanga/Level1.json")
Tracker:AddLocations("locations/lake_orangatanga/Level2.json")
Tracker:AddLocations("locations/lake_orangatanga/Level3.json")
Tracker:AddLocations("locations/lake_orangatanga/Level4.json")
Tracker:AddLocations("locations/lake_orangatanga/Level5.json")
Tracker:AddLocations("locations/lake_orangatanga/Boss.json")
Tracker:AddLocations("locations/lake_orangatanga/Cave.json")

Tracker:AddLocations("locations/kremwood_forest/Level1.json")
Tracker:AddLocations("locations/kremwood_forest/Level2.json")
Tracker:AddLocations("locations/kremwood_forest/Level3.json")
Tracker:AddLocations("locations/kremwood_forest/Level4.json")
Tracker:AddLocations("locations/kremwood_forest/Level5.json")
Tracker:AddLocations("locations/kremwood_forest/Boss.json")
Tracker:AddLocations("locations/kremwood_forest/Cave.json")

Tracker:AddLocations("locations/cotton_top_cove/Level1.json")
Tracker:AddLocations("locations/cotton_top_cove/Level2.json")
Tracker:AddLocations("locations/cotton_top_cove/Level3.json")
Tracker:AddLocations("locations/cotton_top_cove/Level4.json")
Tracker:AddLocations("locations/cotton_top_cove/Level5.json")
Tracker:AddLocations("locations/cotton_top_cove/Boss.json")
Tracker:AddLocations("locations/cotton_top_cove/Cave.json")

Tracker:AddLocations("locations/mekanos/Level1.json")
Tracker:AddLocations("locations/mekanos/Level2.json")
Tracker:AddLocations("locations/mekanos/Level3.json")
Tracker:AddLocations("locations/mekanos/Level4.json")
Tracker:AddLocations("locations/mekanos/Level5.json")
Tracker:AddLocations("locations/mekanos/Boss.json")
Tracker:AddLocations("locations/mekanos/Cave.json")

Tracker:AddLocations("locations/k3/Level1.json")
Tracker:AddLocations("locations/k3/Level2.json")
Tracker:AddLocations("locations/k3/Level3.json")
Tracker:AddLocations("locations/k3/Level4.json")
Tracker:AddLocations("locations/k3/Level5.json")
Tracker:AddLocations("locations/k3/Boss.json")
Tracker:AddLocations("locations/k3/Cave.json")

Tracker:AddLocations("locations/razor_ridge/Level1.json")
Tracker:AddLocations("locations/razor_ridge/Level2.json")
Tracker:AddLocations("locations/razor_ridge/Level3.json")
Tracker:AddLocations("locations/razor_ridge/Level4.json")
Tracker:AddLocations("locations/razor_ridge/Level5.json")
Tracker:AddLocations("locations/razor_ridge/Boss.json")
Tracker:AddLocations("locations/razor_ridge/Cave.json")

Tracker:AddLocations("locations/kaos_kore/Level1.json")
Tracker:AddLocations("locations/kaos_kore/Level2.json")
Tracker:AddLocations("locations/kaos_kore/Level3.json")
Tracker:AddLocations("locations/kaos_kore/Level4.json")
Tracker:AddLocations("locations/kaos_kore/Level5.json")
Tracker:AddLocations("locations/kaos_kore/Boss.json")
Tracker:AddLocations("locations/kaos_kore/Cave.json")

Tracker:AddLocations("locations/krematoa/Level1.json")
Tracker:AddLocations("locations/krematoa/Level2.json")
Tracker:AddLocations("locations/krematoa/Level3.json")
Tracker:AddLocations("locations/krematoa/Level4.json")
Tracker:AddLocations("locations/krematoa/Level5.json")
Tracker:AddLocations("locations/krematoa/Boss.json")

Tracker:AddLocations("locations/BelchaBurrow.json")
Tracker:AddLocations("locations/BountyBeach.json")
Tracker:AddLocations("locations/HillTopHoard.json")
Tracker:AddLocations("locations/KKache.json")
Tracker:AddLocations("locations/KongCave.json")
Tracker:AddLocations("locations/UndercoverCove.json")